using Pulse1x.App.Localization;

namespace Pulse1x.App.Models;

/// <summary>Categorias de instalação da Central Pós-Formatação (agrupam os itens na tela).</summary>
public enum InstallCategory
{
    Drivers,
    Components,
    Browsers,
    Communication,
    Games,
    Utilities,
    Multimedia,
    Productivity,
    Development,
    Security,
    Cloud,
}

/// <summary>Fabricante de hardware associado a um item — usado pela Detecção Inteligente para
/// destacar automaticamente os aplicativos compatíveis com o PC do usuário.</summary>
public enum HwVendor { None, Nvidia, Intel, Amd, Realtek, Asus, Msi, Gigabyte, Acer, Lenovo, Dell, Hp }

/// <summary>Perfis de seleção rápida.</summary>
public enum InstallProfile { Gamer, Basic, Developer, Complete }

/// <summary>
/// Um aplicativo/componente instalável. A instalação usa SEMPRE fonte oficial: quando há
/// <see cref="WingetId"/>, instala pelo Windows Package Manager (winget, que baixa do
/// publicador oficial); quando não, abre a <see cref="Url"/> oficial do fabricante para
/// download manual (caso de drivers e ferramentas OEM que não estão no winget).
/// </summary>
public sealed record AppEntry(
    string Id,
    string Name,
    string DescPt,
    string DescEn,
    string Publisher,
    string Size,
    InstallCategory Category,
    string? WingetId,
    string? Url = null,
    HwVendor Vendor = HwVendor.None,
    bool RecommendedDefault = false)
{
    /// <summary>Descrição no idioma atual da interface.</summary>
    public string Description => Loc.Instance.Language == AppLanguage.English ? DescEn : DescPt;

    /// <summary>True quando a instalação é feita pelo winget (fonte oficial automatizada).</summary>
    public bool UsesWinget => !string.IsNullOrEmpty(WingetId);
}

/// <summary>Uma "Configuração Recomendada" aplicável uma vez (não é um toggle persistente).</summary>
public sealed record RecommendedSetting(
    string Id,
    string TitlePt,
    string TitleEn,
    string DescPt,
    string DescEn,
    bool RecommendedDefault = false)
{
    public string Title => Loc.Instance.Language == AppLanguage.English ? TitleEn : TitlePt;
    public string Description => Loc.Instance.Language == AppLanguage.English ? DescEn : DescPt;
}

/// <summary>
/// Catálogo estático da Central Pós-Formatação: a lista de aplicativos/componentes, as
/// configurações recomendadas e os perfis prontos. Mantido como dado puro (sem lógica de UI)
/// para ficar fácil de revisar e estender. Os IDs de winget apontam para publicadores oficiais.
/// </summary>
public static class PostFormatCatalog
{
    public static readonly IReadOnlyList<AppEntry> Apps = new List<AppEntry>
    {
        // ===================== Drivers e Fabricantes — NVIDIA =====================
        new("nvidia_app", "NVIDIA App",
            "Painel unificado da NVIDIA: drivers, otimização de jogos e gravação.",
            "NVIDIA's unified hub: drivers, game optimization and capture.",
            "NVIDIA", "~120 MB", InstallCategory.Drivers, null,
            "https://www.nvidia.com/en-us/software/nvidia-app/", HwVendor.Nvidia),
        new("nvidia_geforce_experience", "GeForce Experience",
            "Mantém os drivers GeForce atualizados e otimiza as configurações dos jogos.",
            "Keeps GeForce drivers updated and optimizes game settings.",
            "NVIDIA", "~120 MB", InstallCategory.Drivers, null,
            "https://www.nvidia.com/en-us/geforce/geforce-experience/", HwVendor.Nvidia),
        new("nvidia_driver", "Driver NVIDIA (mais recente)",
            "Página oficial para baixar o driver gráfico NVIDIA mais recente para sua GPU.",
            "Official page to download the latest NVIDIA graphics driver for your GPU.",
            "NVIDIA", "~700 MB", InstallCategory.Drivers, null,
            "https://www.nvidia.com/Download/index.aspx", HwVendor.Nvidia),
        new("nvidia_broadcast", "NVIDIA Broadcast",
            "Remove ruído do microfone, desfoca o fundo e melhora a webcam por IA (placas RTX).",
            "AI mic noise removal, background blur and webcam effects (RTX cards).",
            "NVIDIA", "~250 MB", InstallCategory.Drivers, null,
            "https://www.nvidia.com/en-us/geforce/broadcasting/broadcast-app/", HwVendor.Nvidia),
        new("nvidia_frameview", "NVIDIA FrameView",
            "Mede FPS, consumo de energia e desempenho em jogos.",
            "Measures FPS, power draw and gaming performance.",
            "NVIDIA", "~40 MB", InstallCategory.Drivers, "Nvidia.FrameView", null, HwVendor.Nvidia),

        // ===================== Drivers e Fabricantes — Intel =====================
        new("intel_dsa", "Intel Driver & Support Assistant",
            "Detecta e instala automaticamente os drivers Intel mais recentes.",
            "Automatically detects and installs the latest Intel drivers.",
            "Intel", "~30 MB", InstallCategory.Drivers, "Intel.IntelDriverAndSupportAssistant", null, HwVendor.Intel),
        new("intel_gcc", "Intel Graphics Command Center",
            "Ajusta resolução, cores e desempenho dos gráficos integrados Intel.",
            "Tunes resolution, color and performance of Intel integrated graphics.",
            "Intel", "~Loja", InstallCategory.Drivers, null,
            "https://apps.microsoft.com/detail/9plfnlntmn83", HwVendor.Intel),
        new("intel_arc", "Intel Arc Control",
            "Painel das placas Intel Arc: drivers, overclock e gravação.",
            "Control panel for Intel Arc cards: drivers, overclock and capture.",
            "Intel", "~200 MB", InstallCategory.Drivers, null,
            "https://www.intel.com/content/www/us/en/download/726609/intel-arc-control.html", HwVendor.Intel),
        new("intel_xtu", "Intel Extreme Tuning Utility (XTU)",
            "Overclock e monitoramento avançado de processadores Intel.",
            "Overclocking and advanced monitoring for Intel processors.",
            "Intel", "~80 MB", InstallCategory.Drivers, "Intel.IntelExtremeTuningUtility", null, HwVendor.Intel),

        // ===================== Drivers e Fabricantes — AMD =====================
        new("amd_adrenalin", "AMD Software: Adrenalin Edition",
            "Driver e painel das placas Radeon: jogos, gravação e overclock.",
            "Driver and control panel for Radeon cards: gaming, capture and overclock.",
            "AMD", "~600 MB", InstallCategory.Drivers, null,
            "https://www.amd.com/en/support", HwVendor.Amd),
        new("amd_ryzen_master", "AMD Ryzen Master",
            "Overclock e monitoramento de processadores AMD Ryzen.",
            "Overclocking and monitoring for AMD Ryzen processors.",
            "AMD", "~60 MB", InstallCategory.Drivers, null,
            "https://www.amd.com/en/technologies/ryzen-master", HwVendor.Amd),
        new("amd_chipset", "AMD Chipset Drivers",
            "Drivers de chipset para placas-mãe AMD (essencial após formatar).",
            "Chipset drivers for AMD motherboards (essential after a fresh install).",
            "AMD", "~50 MB", InstallCategory.Drivers, null,
            "https://www.amd.com/en/support/chipsets", HwVendor.Amd),
        new("amd_cleanup", "AMD Cleanup Utility",
            "Remove completamente drivers AMD antigos antes de uma instalação limpa.",
            "Fully removes old AMD drivers before a clean install.",
            "AMD", "~5 MB", InstallCategory.Drivers, null,
            "https://www.amd.com/en/support/kb/faq/gpu-601", HwVendor.Amd),

        // ===================== Drivers e Fabricantes — Realtek =====================
        new("realtek_audio_console", "Realtek Audio Console",
            "Equaliza e ajusta o áudio Realtek integrado da placa-mãe.",
            "Equalizes and tunes the motherboard's integrated Realtek audio.",
            "Realtek", "~Loja", InstallCategory.Drivers, null,
            "https://apps.microsoft.com/detail/9p2b8mcsvpln", HwVendor.Realtek),
        new("realtek_audio_driver", "Drivers de áudio Realtek",
            "Página oficial dos drivers de áudio Realtek de alta definição.",
            "Official page for Realtek high-definition audio drivers.",
            "Realtek", "~40 MB", InstallCategory.Drivers, null,
            "https://www.realtek.com/en/downloads", HwVendor.Realtek),

        // ===================== Fabricantes de Notebook / Placa-Mãe =====================
        new("asus_armoury_crate", "Armoury Crate (ASUS)",
            "Central ASUS/ROG: drivers, iluminação RGB e perfis de desempenho.",
            "ASUS/ROG hub: drivers, RGB lighting and performance profiles.",
            "ASUS", "~300 MB", InstallCategory.Drivers, null,
            "https://www.asus.com/supportonly/armoury%20crate/helpdesk_download/", HwVendor.Asus),
        new("asus_myasus", "MyASUS",
            "Suporte, diagnóstico e atualizações para notebooks ASUS.",
            "Support, diagnostics and updates for ASUS laptops.",
            "ASUS", "~Loja", InstallCategory.Drivers, null,
            "https://apps.microsoft.com/detail/9n7r5s6b0zz8", HwVendor.Asus),
        new("msi_center", "MSI Center",
            "Central MSI: drivers, monitoramento e perfis de desempenho.",
            "MSI hub: drivers, monitoring and performance profiles.",
            "MSI", "~250 MB", InstallCategory.Drivers, null,
            "https://www.msi.com/Landing/MSI-Center", HwVendor.Msi),
        new("gigabyte_control_center", "Gigabyte Control Center",
            "Central Gigabyte/AORUS: drivers, RGB e ajustes do sistema.",
            "Gigabyte/AORUS hub: drivers, RGB and system tuning.",
            "Gigabyte", "~250 MB", InstallCategory.Drivers, null,
            "https://www.gigabyte.com/Support/Utility", HwVendor.Gigabyte),
        new("acer_care_center", "Acer Care Center",
            "Diagnóstico, atualizações e suporte para equipamentos Acer.",
            "Diagnostics, updates and support for Acer machines.",
            "Acer", "~Site", InstallCategory.Drivers, null,
            "https://www.acer.com/us-en/support", HwVendor.Acer),
        new("lenovo_vantage", "Lenovo Vantage",
            "Atualizações de driver, garantia e ajustes para equipamentos Lenovo.",
            "Driver updates, warranty and tuning for Lenovo machines.",
            "Lenovo", "~Loja", InstallCategory.Drivers, null,
            "https://apps.microsoft.com/detail/9wzdncrfj4mv", HwVendor.Lenovo),
        new("dell_supportassist", "Dell SupportAssist",
            "Detecção automática de drivers e diagnóstico para equipamentos Dell.",
            "Automatic driver detection and diagnostics for Dell machines.",
            "Dell", "~80 MB", InstallCategory.Drivers, null,
            "https://www.dell.com/support/contents/category/product-support/self-support-knowledgebase/software-and-downloads/supportassist", HwVendor.Dell),
        new("hp_support_assistant", "HP Support Assistant",
            "Atualizações, drivers e diagnóstico para equipamentos HP.",
            "Updates, drivers and diagnostics for HP machines.",
            "HP", "~50 MB", InstallCategory.Drivers, null,
            "https://support.hp.com/us-en/help/hp-support-assistant", HwVendor.Hp),

        // ===================== Componentes Essenciais =====================
        new("vcredist_x64", "Visual C++ Redistributable (x64)",
            "Bibliotecas que MUITOS programas e jogos exigem para rodar (64 bits).",
            "Libraries that MANY programs and games require to run (64-bit).",
            "Microsoft", "~25 MB", InstallCategory.Components, "Microsoft.VCRedist.2015+.x64", null, HwVendor.None, true),
        new("vcredist_x86", "Visual C++ Redistributable (x86)",
            "Versão 32 bits das bibliotecas Visual C++, exigida por vários programas antigos.",
            "32-bit version of the Visual C++ libraries, required by many older programs.",
            "Microsoft", "~25 MB", InstallCategory.Components, "Microsoft.VCRedist.2015+.x86", null, HwVendor.None, true),
        new("vcredist_2013", "Visual C++ Redistributable 2013",
            "Versão 2013 das bibliotecas Visual C++, exigida por alguns jogos e programas.",
            "2013 version of the Visual C++ libraries, required by some games and programs.",
            "Microsoft", "~15 MB", InstallCategory.Components, "Microsoft.VCRedist.2013.x64", null, HwVendor.None, true),
        new("dotnet_desktop", ".NET Desktop Runtime 8",
            "Plataforma para rodar aplicativos de desktop modernos feitos em .NET.",
            "Runtime to run modern .NET desktop applications.",
            "Microsoft", "~55 MB", InstallCategory.Components, "Microsoft.DotNet.DesktopRuntime.8", null, HwVendor.None, true),
        new("dotnet_runtime", ".NET Runtime 8",
            "Plataforma base para executar aplicativos e serviços feitos em .NET.",
            "Base runtime to execute .NET applications and services.",
            "Microsoft", "~25 MB", InstallCategory.Components, "Microsoft.DotNet.Runtime.8", null, HwVendor.None),
        new("directx", "DirectX Runtime",
            "Componentes gráficos e de áudio exigidos por praticamente todos os jogos.",
            "Graphics and audio components required by virtually every game.",
            "Microsoft", "~10 MB", InstallCategory.Components, "Microsoft.DirectX", null, HwVendor.None, true),
        new("webview2", "Edge WebView2 Runtime",
            "Motor que muitos aplicativos usam para exibir conteúdo web internamente.",
            "Engine many apps use to render web content internally.",
            "Microsoft", "~120 MB", InstallCategory.Components, "Microsoft.EdgeWebView2Runtime", null, HwVendor.None, true),
        new("vcredist_2013_x86", "Visual C++ Redistributable 2013 (x86)",
            "Versão 32 bits das bibliotecas Visual C++ 2013.",
            "32-bit version of the Visual C++ 2013 libraries.",
            "Microsoft", "~12 MB", InstallCategory.Components, "Microsoft.VCRedist.2013.x86", null, HwVendor.None, true),
        new("vcredist_2012_x64", "Visual C++ Redistributable 2012 (x64)",
            "Bibliotecas Visual C++ 2012 (64 bits), exigidas por jogos e programas mais antigos.",
            "Visual C++ 2012 libraries (64-bit), required by older games and programs.",
            "Microsoft", "~14 MB", InstallCategory.Components, "Microsoft.VCRedist.2012.x64", null, HwVendor.None, true),
        new("vcredist_2012_x86", "Visual C++ Redistributable 2012 (x86)",
            "Versão 32 bits das bibliotecas Visual C++ 2012.",
            "32-bit version of the Visual C++ 2012 libraries.",
            "Microsoft", "~12 MB", InstallCategory.Components, "Microsoft.VCRedist.2012.x86", null, HwVendor.None, true),
        new("vcredist_2010", "Visual C++ Redistributable 2010 (x64)",
            "Bibliotecas Visual C++ 2010, exigidas por vários programas legados.",
            "Visual C++ 2010 libraries, required by several legacy programs.",
            "Microsoft", "~10 MB", InstallCategory.Components, "Microsoft.VCRedist.2010.x64"),
        new("vcredist_2010_x86", "Visual C++ Redistributable 2010 (x86)",
            "Versão 32 bits das bibliotecas Visual C++ 2010.",
            "32-bit version of the Visual C++ 2010 libraries.",
            "Microsoft", "~8 MB", InstallCategory.Components, "Microsoft.VCRedist.2010.x86"),
        new("vcredist_2008", "Visual C++ Redistributable 2008 (x64)",
            "Bibliotecas Visual C++ 2008, exigidas por programas e jogos antigos.",
            "Visual C++ 2008 libraries, required by old programs and games.",
            "Microsoft", "~8 MB", InstallCategory.Components, "Microsoft.VCRedist.2008.x64"),
        new("vcredist_2008_x86", "Visual C++ Redistributable 2008 (x86)",
            "Versão 32 bits das bibliotecas Visual C++ 2008.",
            "32-bit version of the Visual C++ 2008 libraries.",
            "Microsoft", "~6 MB", InstallCategory.Components, "Microsoft.VCRedist.2008.x86"),
        new("dotnet_desktop_9", ".NET Desktop Runtime 9",
            "Plataforma para rodar aplicativos de desktop em .NET 9 (versão mais recente).",
            "Runtime to run .NET 9 desktop applications (latest version).",
            "Microsoft", "~58 MB", InstallCategory.Components, "Microsoft.DotNet.DesktopRuntime.9"),
        new("dotnet_desktop_7", ".NET Desktop Runtime 7",
            "Plataforma para rodar aplicativos de desktop em .NET 7.",
            "Runtime to run .NET 7 desktop applications.",
            "Microsoft", "~55 MB", InstallCategory.Components, "Microsoft.DotNet.DesktopRuntime.7"),
        new("dotnet_desktop_6", ".NET Desktop Runtime 6",
            "Plataforma para rodar aplicativos de desktop em .NET 6 (LTS, ainda muito usado).",
            "Runtime to run .NET 6 desktop applications (LTS, still widely used).",
            "Microsoft", "~53 MB", InstallCategory.Components, "Microsoft.DotNet.DesktopRuntime.6"),
        new("java_runtime", "Java (Temurin JRE 21)",
            "Ambiente de execução Java, exigido por muitos programas e jogos (ex.: Minecraft).",
            "Java runtime environment, required by many programs and games (e.g. Minecraft).",
            "Eclipse Adoptium", "~45 MB", InstallCategory.Components, "EclipseAdoptium.Temurin.21.JRE"),

        // ===================== Navegadores =====================
        new("chrome", "Google Chrome",
            "Navegador rápido e popular do Google.",
            "Google's fast and popular web browser.",
            "Google", "~100 MB", InstallCategory.Browsers, "Google.Chrome", null, HwVendor.None, true),
        new("firefox", "Mozilla Firefox",
            "Navegador focado em privacidade e personalização.",
            "Privacy-focused, customizable web browser.",
            "Mozilla", "~60 MB", InstallCategory.Browsers, "Mozilla.Firefox"),
        new("opera", "Opera",
            "Navegador com VPN integrada e recursos para jogos.",
            "Browser with built-in VPN and gaming features.",
            "Opera", "~80 MB", InstallCategory.Browsers, "Opera.Opera"),
        new("brave", "Brave",
            "Navegador com bloqueio de anúncios e rastreadores por padrão.",
            "Browser that blocks ads and trackers by default.",
            "Brave", "~120 MB", InstallCategory.Browsers, "Brave.Brave"),
        new("edge", "Microsoft Edge",
            "Navegador da Microsoft (reinstalar/reparar quando necessário).",
            "Microsoft's web browser (reinstall/repair when needed).",
            "Microsoft", "~150 MB", InstallCategory.Browsers, "Microsoft.Edge"),
        new("vivaldi", "Vivaldi",
            "Navegador altamente personalizável, baseado no Chromium.",
            "Highly customizable Chromium-based browser.",
            "Vivaldi", "~100 MB", InstallCategory.Browsers, "Vivaldi.Vivaldi"),
        new("librewolf", "LibreWolf",
            "Firefox endurecido para privacidade, sem telemetria.",
            "Privacy-hardened Firefox fork, no telemetry.",
            "LibreWolf", "~70 MB", InstallCategory.Browsers, "LibreWolf.LibreWolf"),
        new("torbrowser", "Tor Browser",
            "Navegador para navegação anônima pela rede Tor.",
            "Browser for anonymous browsing over the Tor network.",
            "The Tor Project", "~120 MB", InstallCategory.Browsers, "TorProject.TorBrowser"),

        // ===================== Comunicação =====================
        new("discord", "Discord",
            "Chat de voz, vídeo e texto popular entre gamers e comunidades.",
            "Voice, video and text chat popular with gamers and communities.",
            "Discord", "~90 MB", InstallCategory.Communication, "Discord.Discord", null, HwVendor.None, true),
        new("telegram", "Telegram Desktop",
            "Mensageiro rápido, leve e seguro.",
            "Fast, lightweight and secure messenger.",
            "Telegram", "~40 MB", InstallCategory.Communication, "Telegram.TelegramDesktop"),
        new("whatsapp", "WhatsApp Desktop",
            "Aplicativo de desktop do WhatsApp.",
            "WhatsApp desktop application.",
            "WhatsApp", "~150 MB", InstallCategory.Communication, "9NKSQGP7F2NH",
            "https://apps.microsoft.com/detail/9nksqgp7f2nh"),
        new("zoom", "Zoom",
            "Reuniões e chamadas de vídeo.",
            "Video meetings and calls.",
            "Zoom", "~50 MB", InstallCategory.Communication, "Zoom.Zoom"),
        new("teams", "Microsoft Teams",
            "Reuniões, chat e colaboração da Microsoft.",
            "Microsoft meetings, chat and collaboration.",
            "Microsoft", "~120 MB", InstallCategory.Communication, "Microsoft.Teams"),
        new("slack", "Slack",
            "Comunicação e colaboração para equipes de trabalho.",
            "Communication and collaboration for work teams.",
            "Slack", "~130 MB", InstallCategory.Communication, "SlackTechnologies.Slack"),
        new("signal", "Signal",
            "Mensageiro com criptografia ponta a ponta, focado em privacidade.",
            "End-to-end encrypted, privacy-focused messenger.",
            "Signal", "~120 MB", InstallCategory.Communication, "OpenWhisperSystems.Signal"),
        new("thunderbird", "Mozilla Thunderbird",
            "Cliente de e-mail gratuito e completo da Mozilla.",
            "Mozilla's free, full-featured email client.",
            "Mozilla", "~80 MB", InstallCategory.Communication, "Mozilla.Thunderbird"),

        // ===================== Jogos =====================
        new("steam", "Steam",
            "A maior loja e plataforma de jogos para PC.",
            "The largest PC game store and platform.",
            "Valve", "~3 MB", InstallCategory.Games, "Valve.Steam", null, HwVendor.None, true),
        new("epic", "Epic Games Launcher",
            "Loja da Epic com jogos grátis semanais e Fortnite.",
            "Epic's store with weekly free games and Fortnite.",
            "Epic Games", "~80 MB", InstallCategory.Games, "EpicGames.EpicGamesLauncher"),
        new("ea_app", "EA App",
            "Plataforma de jogos da Electronic Arts.",
            "Electronic Arts gaming platform.",
            "Electronic Arts", "~150 MB", InstallCategory.Games, "ElectronicArts.EADesktop"),
        new("ubisoft", "Ubisoft Connect",
            "Plataforma de jogos da Ubisoft.",
            "Ubisoft gaming platform.",
            "Ubisoft", "~80 MB", InstallCategory.Games, "Ubisoft.Connect"),
        new("battlenet", "Battle.net",
            "Plataforma da Blizzard (Diablo, Overwatch, Call of Duty).",
            "Blizzard platform (Diablo, Overwatch, Call of Duty).",
            "Blizzard", "~120 MB", InstallCategory.Games, "Blizzard.BattleNet"),
        new("riot", "Riot Client",
            "Cliente da Riot (League of Legends, VALORANT).",
            "Riot client (League of Legends, VALORANT).",
            "Riot Games", "~Site", InstallCategory.Games, null,
            "https://www.riotgames.com/en/riot-client"),
        new("xbox", "Xbox App",
            "Aplicativo Xbox com o Game Pass para PC.",
            "Xbox app with PC Game Pass.",
            "Microsoft", "~Loja", InstallCategory.Games, "9MV0B5HZVK9Z",
            "https://apps.microsoft.com/detail/9mv0b5hzvk9z"),
        new("gog", "GOG Galaxy",
            "Loja de jogos sem DRM da GOG.",
            "GOG's DRM-free game store.",
            "GOG", "~200 MB", InstallCategory.Games, "GOG.Galaxy"),
        new("minecraft", "Minecraft Launcher",
            "Inicializador oficial do Minecraft (Java e Bedrock).",
            "Official Minecraft launcher (Java and Bedrock).",
            "Mojang", "~30 MB", InstallCategory.Games, "Mojang.MinecraftLauncher"),
        new("playnite", "Playnite",
            "Reúne todas as suas bibliotecas de jogos (Steam, Epic, GOG...) em um só lugar.",
            "Brings all your game libraries (Steam, Epic, GOG...) into one place.",
            "Playnite", "~120 MB", InstallCategory.Games, "Playnite.Playnite"),
        new("heroic", "Heroic Games Launcher",
            "Cliente alternativo para Epic Games, GOG e Amazon Prime Gaming.",
            "Alternative client for Epic Games, GOG and Amazon Prime Gaming.",
            "Heroic", "~120 MB", InstallCategory.Games, "HeroicGamesLauncher.HeroicGamesLauncher"),
        new("itch", "itch.io",
            "Loja e cliente de jogos indie.",
            "Indie game store and client.",
            "itch.io", "~80 MB", InstallCategory.Games, "ItchIo.Itch"),

        // ===================== Utilidades =====================
        new("7zip", "7-Zip",
            "Compactador de arquivos leve, gratuito e completo.",
            "Lightweight, free and powerful file archiver.",
            "Igor Pavlov", "~2 MB", InstallCategory.Utilities, "7zip.7zip", null, HwVendor.None, true),
        new("winrar", "WinRAR",
            "Compactador de arquivos clássico (RAR e ZIP).",
            "Classic file archiver (RAR and ZIP).",
            "RARLAB", "~3 MB", InstallCategory.Utilities, "RARLab.WinRAR"),
        new("everything", "Everything",
            "Busca instantânea de arquivos por nome em todo o PC.",
            "Instant file-name search across the whole PC.",
            "voidtools", "~2 MB", InstallCategory.Utilities, "voidtools.Everything"),
        new("powertoys", "PowerToys",
            "Conjunto de utilitários avançados da Microsoft para Windows.",
            "Microsoft's set of advanced power-user utilities for Windows.",
            "Microsoft", "~250 MB", InstallCategory.Utilities, "Microsoft.PowerToys"),
        new("cpuz", "CPU-Z",
            "Mostra informações detalhadas do processador, placa-mãe e memória.",
            "Shows detailed CPU, motherboard and memory information.",
            "CPUID", "~5 MB", InstallCategory.Utilities, "CPUID.CPU-Z"),
        new("gpuz", "GPU-Z",
            "Mostra informações detalhadas e sensores da placa de vídeo.",
            "Shows detailed graphics-card information and sensors.",
            "TechPowerUp", "~10 MB", InstallCategory.Utilities, "TechPowerUp.GPU-Z"),
        new("hwinfo", "HWiNFO",
            "Monitoramento completo de sensores de hardware (temperaturas, tensões).",
            "Comprehensive hardware sensor monitoring (temperatures, voltages).",
            "REALiX", "~10 MB", InstallCategory.Utilities, "REALiX.HWiNFO"),
        new("crystaldiskinfo", "CrystalDiskInfo",
            "Mostra a saúde (SMART) de HDs e SSDs.",
            "Shows the SMART health of HDDs and SSDs.",
            "Crystal Dew World", "~10 MB", InstallCategory.Utilities, "CrystalDewWorld.CrystalDiskInfo"),
        new("crystaldiskmark", "CrystalDiskMark",
            "Testa a velocidade de leitura e gravação de discos.",
            "Benchmarks disk read and write speed.",
            "Crystal Dew World", "~10 MB", InstallCategory.Utilities, "CrystalDewWorld.CrystalDiskMark"),
        new("rufus", "Rufus",
            "Cria pen drives bootáveis (instalação do Windows e outros).",
            "Creates bootable USB drives (Windows install and more).",
            "Akeo", "~1 MB", InstallCategory.Utilities, "Rufus.Rufus"),
        new("windows_terminal", "Windows Terminal",
            "Terminal moderno com abas para PowerShell, CMD e WSL.",
            "Modern tabbed terminal for PowerShell, CMD and WSL.",
            "Microsoft", "~Loja", InstallCategory.Utilities, "Microsoft.WindowsTerminal"),
        new("powershell7", "PowerShell 7",
            "A versão moderna e multiplataforma do PowerShell.",
            "The modern, cross-platform version of PowerShell.",
            "Microsoft", "~110 MB", InstallCategory.Utilities, "Microsoft.PowerShell"),
        new("nanazip", "NanaZip",
            "Compactador de arquivos moderno (fork do 7-Zip, integrado ao Windows 11).",
            "Modern file archiver (7-Zip fork, integrated with Windows 11).",
            "M2Team", "~3 MB", InstallCategory.Utilities, "M2Team.NanaZip"),
        new("qbittorrent", "qBittorrent",
            "Cliente de torrent leve, gratuito e sem anúncios.",
            "Lightweight, free, ad-free torrent client.",
            "qBittorrent", "~30 MB", InstallCategory.Utilities, "qBittorrent.qBittorrent"),
        new("sharex", "ShareX",
            "Captura de tela e gravação avançadas, com upload automático.",
            "Advanced screen capture and recording, with automatic upload.",
            "ShareX Team", "~50 MB", InstallCategory.Utilities, "ShareX.ShareX"),
        new("greenshot", "Greenshot",
            "Ferramenta simples e rápida de captura de tela.",
            "Simple, fast screenshot tool.",
            "Greenshot", "~3 MB", InstallCategory.Utilities, "Greenshot.Greenshot"),
        new("wiztree", "WizTree",
            "Mostra rapidamente o que está ocupando espaço no disco.",
            "Quickly shows what is taking up disk space.",
            "Antibody Software", "~5 MB", InstallCategory.Utilities, "AntibodySoftware.WizTree"),
        new("windirstat", "WinDirStat",
            "Visualiza o uso do disco em um mapa de blocos.",
            "Visualizes disk usage as a treemap.",
            "WinDirStat", "~2 MB", InstallCategory.Utilities, "WinDirStat.WinDirStat"),
        new("treesize", "TreeSize Free",
            "Analisa o tamanho de pastas e encontra o que ocupa espaço.",
            "Analyzes folder sizes and finds what takes up space.",
            "JAM Software", "~10 MB", InstallCategory.Utilities, "JAMSoftware.TreeSize.Free"),
        new("revo", "Revo Uninstaller",
            "Desinstala programas e remove os restos (registro e arquivos) que sobram.",
            "Uninstalls programs and removes leftovers (registry and files).",
            "VS Revo Group", "~15 MB", InstallCategory.Utilities, "RevoUninstaller.RevoUninstaller"),
        new("bcuninstaller", "Bulk Crap Uninstaller",
            "Remove vários programas de uma vez, inclusive bloatware difícil.",
            "Removes many programs at once, including stubborn bloatware.",
            "Bulk Crap Uninstaller", "~30 MB", InstallCategory.Utilities, "Klocman.BulkCrapUninstaller"),
        new("bleachbit", "BleachBit",
            "Limpa arquivos temporários e libera espaço em disco.",
            "Cleans temporary files and frees disk space.",
            "BleachBit", "~30 MB", InstallCategory.Utilities, "BleachBit.BleachBit"),
        new("ddu", "Display Driver Uninstaller (DDU)",
            "Remove completamente drivers de vídeo antigos antes de uma instalação limpa.",
            "Completely removes old graphics drivers before a clean install.",
            "Wagnardsoft", "~15 MB", InstallCategory.Utilities, "Wagnardsoft.DisplayDriverUninstaller"),
        new("sysinternals", "Sysinternals Suite",
            "Conjunto de ferramentas avançadas da Microsoft (Process Explorer, Autoruns...).",
            "Microsoft's set of advanced tools (Process Explorer, Autoruns...).",
            "Microsoft", "~50 MB", InstallCategory.Utilities, "Microsoft.Sysinternals.Suite"),
        new("winscp", "WinSCP",
            "Cliente de transferência de arquivos SFTP, FTP e SCP.",
            "SFTP, FTP and SCP file transfer client.",
            "WinSCP", "~12 MB", InstallCategory.Utilities, "WinSCP.WinSCP"),
        new("anydesk", "AnyDesk",
            "Acesso e suporte remoto rápido a outros computadores.",
            "Fast remote access and support to other computers.",
            "AnyDesk", "~5 MB", InstallCategory.Utilities, "AnyDesk.AnyDesk"),
        new("teamviewer", "TeamViewer",
            "Acesso remoto e suporte (gratuito para uso pessoal).",
            "Remote access and support (free for personal use).",
            "TeamViewer", "~50 MB", InstallCategory.Utilities, "TeamViewer.TeamViewer"),

        // ===================== Multimídia =====================
        new("vlc", "VLC Media Player",
            "Reproduz praticamente qualquer formato de vídeo e áudio.",
            "Plays virtually any video and audio format.",
            "VideoLAN", "~40 MB", InstallCategory.Multimedia, "VideoLAN.VLC", null, HwVendor.None, true),
        new("spotify", "Spotify",
            "Streaming de música e podcasts.",
            "Music and podcast streaming.",
            "Spotify", "~120 MB", InstallCategory.Multimedia, "Spotify.Spotify"),
        new("obs", "OBS Studio",
            "Gravação e transmissão (live) de tela e jogos.",
            "Screen and game recording and streaming.",
            "OBS Project", "~120 MB", InstallCategory.Multimedia, "OBSProject.OBSStudio"),
        new("audacity", "Audacity",
            "Editor de áudio gratuito e completo.",
            "Free, full-featured audio editor.",
            "Audacity", "~40 MB", InstallCategory.Multimedia, "Audacity.Audacity"),
        new("mpchc", "MPC-HC",
            "Reprodutor de mídia leve e clássico para Windows.",
            "Lightweight, classic media player for Windows.",
            "MPC-HC Team", "~15 MB", InstallCategory.Multimedia, "clsid2.mpc-hc"),
        new("klite", "K-Lite Codec Pack",
            "Pacote de codecs para reproduzir praticamente qualquer mídia.",
            "Codec pack to play virtually any media.",
            "KLCP", "~60 MB", InstallCategory.Multimedia, "CodecGuide.K-LiteCodecPack.Standard"),
        new("potplayer", "PotPlayer",
            "Reprodutor de mídia completo e altamente configurável.",
            "Full-featured, highly configurable media player.",
            "Kakao", "~30 MB", InstallCategory.Multimedia, "Daum.PotPlayer"),
        new("handbrake", "HandBrake",
            "Conversor de vídeo gratuito (recodifica para MP4, MKV...).",
            "Free video transcoder (re-encodes to MP4, MKV...).",
            "HandBrake", "~25 MB", InstallCategory.Multimedia, "HandBrake.HandBrake"),
        new("ffmpeg", "FFmpeg",
            "Ferramenta de linha de comando para converter áudio e vídeo.",
            "Command-line tool to convert audio and video.",
            "FFmpeg", "~80 MB", InstallCategory.Multimedia, "Gyan.FFmpeg"),
        new("gimp", "GIMP",
            "Editor de imagens gratuito e poderoso (alternativa ao Photoshop).",
            "Free, powerful image editor (Photoshop alternative).",
            "GIMP", "~250 MB", InstallCategory.Multimedia, "GIMP.GIMP"),
        new("paintnet", "Paint.NET",
            "Editor de imagens simples e leve, mais avançado que o Paint.",
            "Simple, lightweight image editor, more advanced than Paint.",
            "dotPDN", "~12 MB", InstallCategory.Multimedia, "dotPDN.PaintDotNet"),
        new("krita", "Krita",
            "Programa de pintura digital gratuito, voltado a artistas.",
            "Free digital painting program aimed at artists.",
            "KDE", "~250 MB", InstallCategory.Multimedia, "KDE.Krita"),
        new("inkscape", "Inkscape",
            "Editor de gráficos vetoriais gratuito (alternativa ao Illustrator).",
            "Free vector graphics editor (Illustrator alternative).",
            "Inkscape", "~120 MB", InstallCategory.Multimedia, "Inkscape.Inkscape"),
        new("blender", "Blender",
            "Suíte de modelagem, animação e renderização 3D gratuita.",
            "Free 3D modeling, animation and rendering suite.",
            "Blender Foundation", "~350 MB", InstallCategory.Multimedia, "BlenderFoundation.Blender"),

        // ===================== Produtividade =====================
        new("libreoffice", "LibreOffice",
            "Suíte de escritório gratuita (textos, planilhas, apresentações).",
            "Free office suite (documents, spreadsheets, presentations).",
            "The Document Foundation", "~330 MB", InstallCategory.Productivity, "TheDocumentFoundation.LibreOffice"),
        new("onlyoffice", "ONLYOFFICE Desktop Editors",
            "Suíte de escritório com ótima compatibilidade com formatos do Microsoft Office.",
            "Office suite with great compatibility with Microsoft Office formats.",
            "ONLYOFFICE", "~300 MB", InstallCategory.Productivity, "ONLYOFFICE.DesktopEditors"),
        new("acrobat_reader", "Adobe Acrobat Reader",
            "Leitor oficial de arquivos PDF.",
            "Official PDF reader.",
            "Adobe", "~300 MB", InstallCategory.Productivity, "Adobe.Acrobat.Reader.64-bit"),
        new("foxit", "Foxit PDF Reader",
            "Leitor de PDF leve e rápido, alternativa ao Adobe.",
            "Lightweight, fast PDF reader, alternative to Adobe.",
            "Foxit", "~120 MB", InstallCategory.Productivity, "Foxit.FoxitReader"),
        new("obsidian", "Obsidian",
            "Aplicativo de notas e conhecimento baseado em arquivos Markdown locais.",
            "Notes and knowledge app based on local Markdown files.",
            "Obsidian", "~80 MB", InstallCategory.Productivity, "Obsidian.Obsidian"),
        new("notion", "Notion",
            "Notas, documentos, wikis e gerenciamento de projetos em um só app.",
            "Notes, docs, wikis and project management in one app.",
            "Notion", "~100 MB", InstallCategory.Productivity, "Notion.Notion"),

        // ===================== Desenvolvimento =====================
        new("vscode", "Visual Studio Code",
            "Editor de código leve e extensível da Microsoft.",
            "Microsoft's lightweight, extensible code editor.",
            "Microsoft", "~100 MB", InstallCategory.Development, "Microsoft.VisualStudioCode"),
        new("git", "Git",
            "Sistema de controle de versão (essencial para programar).",
            "Version control system (essential for development).",
            "Git", "~60 MB", InstallCategory.Development, "Git.Git"),
        new("python", "Python 3.12",
            "Linguagem de programação Python e seu interpretador.",
            "Python programming language and interpreter.",
            "Python Software Foundation", "~30 MB", InstallCategory.Development, "Python.Python.3.12"),
        new("nodejs", "Node.js (LTS)",
            "Ambiente JavaScript do lado do servidor (versão estável LTS).",
            "Server-side JavaScript runtime (stable LTS version).",
            "OpenJS", "~30 MB", InstallCategory.Development, "OpenJS.NodeJS.LTS"),
        new("notepadpp", "Notepad++",
            "Editor de texto e código rápido e leve.",
            "Fast, lightweight text and code editor.",
            "Notepad++", "~5 MB", InstallCategory.Development, "Notepad++.Notepad++"),
        new("sublime", "Sublime Text",
            "Editor de código rápido e sofisticado.",
            "Fast, sophisticated code editor.",
            "Sublime HQ", "~20 MB", InstallCategory.Development, "SublimeHQ.SublimeText.4"),
        new("github_desktop", "GitHub Desktop",
            "Interface gráfica para Git e GitHub.",
            "Graphical interface for Git and GitHub.",
            "GitHub", "~150 MB", InstallCategory.Development, "GitHub.GitHubDesktop"),
        new("dotnet_sdk", ".NET SDK 8",
            "Kit de desenvolvimento para criar aplicativos em .NET 8.",
            "Development kit to build .NET 8 applications.",
            "Microsoft", "~200 MB", InstallCategory.Development, "Microsoft.DotNet.SDK.8"),
        new("docker", "Docker Desktop",
            "Cria e executa contêineres no Windows (requer WSL2).",
            "Builds and runs containers on Windows (requires WSL2).",
            "Docker", "~600 MB", InstallCategory.Development, "Docker.DockerDesktop"),
        new("postman", "Postman",
            "Plataforma para testar e desenvolver APIs.",
            "Platform to test and develop APIs.",
            "Postman", "~200 MB", InstallCategory.Development, "Postman.Postman"),
        new("dbeaver", "DBeaver",
            "Cliente universal de banco de dados (MySQL, PostgreSQL, SQLite...).",
            "Universal database client (MySQL, PostgreSQL, SQLite...).",
            "DBeaver", "~200 MB", InstallCategory.Development, "DBeaver.DBeaver.Community"),
        new("winmerge", "WinMerge",
            "Compara e mescla arquivos e pastas.",
            "Compares and merges files and folders.",
            "WinMerge", "~20 MB", InstallCategory.Development, "WinMerge.WinMerge"),
        new("jetbrains_toolbox", "JetBrains Toolbox",
            "Gerenciador das IDEs da JetBrains (IntelliJ, PyCharm, Rider...).",
            "Manager for JetBrains IDEs (IntelliJ, PyCharm, Rider...).",
            "JetBrains", "~120 MB", InstallCategory.Development, "JetBrains.Toolbox"),
        new("golang", "Go",
            "Linguagem de programação Go e seu compilador.",
            "Go programming language and compiler.",
            "Google", "~140 MB", InstallCategory.Development, "GoLang.Go"),
        new("rust", "Rust (rustup)",
            "Instalador e gerenciador da linguagem Rust.",
            "Installer and manager for the Rust language.",
            "Rust Foundation", "~10 MB", InstallCategory.Development, "Rustlang.Rustup"),

        // ===================== Segurança =====================
        new("malwarebytes", "Malwarebytes",
            "Antimalware que remove ameaças que o antivírus comum deixa passar.",
            "Anti-malware that removes threats a regular antivirus may miss.",
            "Malwarebytes", "~250 MB", InstallCategory.Security, "Malwarebytes.Malwarebytes"),
        new("bitwarden", "Bitwarden",
            "Gerenciador de senhas seguro e de código aberto.",
            "Secure, open-source password manager.",
            "Bitwarden", "~80 MB", InstallCategory.Security, "Bitwarden.Bitwarden"),
        new("authy", "Authy",
            "Aplicativo de autenticação em duas etapas (2FA).",
            "Two-factor authentication (2FA) app.",
            "Twilio", "~Site", InstallCategory.Security, null,
            "https://authy.com/download/"),
        new("keepassxc", "KeePassXC",
            "Gerenciador de senhas local e de código aberto.",
            "Local, open-source password manager.",
            "KeePassXC Team", "~40 MB", InstallCategory.Security, "KeePassXCTeam.KeePassXC"),
        new("onepassword", "1Password",
            "Gerenciador de senhas comercial, com sincronização na nuvem.",
            "Commercial password manager with cloud sync.",
            "AgileBits", "~120 MB", InstallCategory.Security, "AgileBits.1Password"),
        new("yubico_auth", "Yubico Authenticator",
            "Autenticação em duas etapas (2FA) com chaves YubiKey.",
            "Two-factor authentication (2FA) with YubiKey keys.",
            "Yubico", "~80 MB", InstallCategory.Security, "Yubico.Authenticator"),
        new("protonvpn", "Proton VPN",
            "VPN com foco em privacidade, com plano gratuito.",
            "Privacy-focused VPN with a free tier.",
            "Proton", "~120 MB", InstallCategory.Security, "Proton.ProtonVPN"),
        new("cloudflare_warp", "Cloudflare WARP",
            "VPN/DNS gratuito da Cloudflare que acelera e protege a conexão.",
            "Cloudflare's free VPN/DNS that speeds up and secures the connection.",
            "Cloudflare", "~30 MB", InstallCategory.Security, "Cloudflare.Warp"),
        new("wireshark", "Wireshark",
            "Analisador de tráfego de rede (captura e inspeciona pacotes).",
            "Network traffic analyzer (captures and inspects packets).",
            "Wireshark Foundation", "~80 MB", InstallCategory.Security, "WiresharkFoundation.Wireshark"),

        // ===================== Armazenamento em Nuvem =====================
        new("onedrive", "OneDrive",
            "Armazenamento em nuvem da Microsoft, integrado ao Windows.",
            "Microsoft's cloud storage, integrated with Windows.",
            "Microsoft", "~50 MB", InstallCategory.Cloud, "Microsoft.OneDrive"),
        new("google_drive", "Google Drive",
            "Armazenamento em nuvem do Google para desktop.",
            "Google's cloud storage for desktop.",
            "Google", "~80 MB", InstallCategory.Cloud, "Google.GoogleDrive"),
        new("dropbox", "Dropbox",
            "Armazenamento e sincronização de arquivos na nuvem.",
            "Cloud file storage and sync.",
            "Dropbox", "~120 MB", InstallCategory.Cloud, "Dropbox.Dropbox"),
        new("mega", "MEGA",
            "Armazenamento em nuvem com bastante espaço gratuito e criptografia.",
            "Cloud storage with generous free space and encryption.",
            "MEGA", "~60 MB", InstallCategory.Cloud, "Mega.MEGASync"),
        new("protondrive", "Proton Drive",
            "Armazenamento em nuvem criptografado da Proton.",
            "Proton's encrypted cloud storage.",
            "Proton", "~120 MB", InstallCategory.Cloud, "Proton.ProtonDrive"),
        new("nextcloud", "Nextcloud",
            "Cliente de nuvem privada de código aberto (auto-hospedável).",
            "Open-source private cloud client (self-hostable).",
            "Nextcloud", "~120 MB", InstallCategory.Cloud, "Nextcloud.NextcloudDesktop"),
    };

    public static readonly IReadOnlyList<RecommendedSetting> Settings = new List<RecommendedSetting>
    {
        new("restore_point", "Criar ponto de restauração", "Create a restore point",
            "Cria um ponto de restauração AGORA, para você poder voltar atrás se algo der errado.",
            "Creates a restore point NOW, so you can roll back if something goes wrong.", true),
        new("enable_system_restore", "Ativar proteção do sistema", "Enable System Restore",
            "Liga a Proteção do Sistema no disco C: (necessária para criar pontos de restauração).",
            "Turns on System Protection for drive C: (required to create restore points).", true),
        new("high_performance", "Ativar plano Alto Desempenho", "Enable High Performance plan",
            "Troca o plano de energia para Alto Desempenho (menos economia, mais velocidade).",
            "Switches the power plan to High Performance (less saving, more speed)."),
        new("ultimate_performance", "Ativar Desempenho Máximo", "Enable Ultimate Performance",
            "Cria e ativa o plano oculto Ultimate Performance (ideal para desktops).",
            "Creates and enables the hidden Ultimate Performance plan (ideal for desktops)."),
        new("disable_suggestions", "Desativar sugestões do Windows", "Disable Windows suggestions",
            "Remove dicas, sugestões e anúncios do menu Iniciar e da tela de bloqueio.",
            "Removes tips, suggestions and ads from the Start menu and lock screen.", true),
        new("reduce_telemetry", "Reduzir telemetria opcional", "Reduce optional telemetry",
            "Reduz os dados de diagnóstico opcionais enviados à Microsoft para o mínimo.",
            "Reduces optional diagnostic data sent to Microsoft to the minimum.", true),
        new("show_extensions", "Mostrar extensões de arquivos", "Show file extensions",
            "Exibe a extensão (.exe, .pdf...) dos arquivos no Explorador — ajuda a evitar golpes.",
            "Shows file extensions (.exe, .pdf...) in Explorer — helps avoid scams.", true),
        new("show_hidden", "Mostrar arquivos ocultos", "Show hidden files",
            "Exibe arquivos e pastas ocultos no Explorador de Arquivos.",
            "Shows hidden files and folders in File Explorer."),
        new("explorer_this_pc", "Abrir Explorador em \"Este Computador\"", "Open Explorer to \"This PC\"",
            "Faz o Explorador de Arquivos abrir em \"Este Computador\" em vez do Acesso Rápido.",
            "Makes File Explorer open to \"This PC\" instead of Quick Access.", true),
        new("manage_startup", "Revisar apps da inicialização", "Review startup apps",
            "Abre o gerenciador de inicialização para você desativar programas desnecessários.",
            "Opens the startup manager so you can disable unnecessary programs."),
    };

    // Perfis prontos: cada um seleciona um conjunto de IDs. Drivers compatíveis são adicionados
    // pela Detecção Inteligente em cima destes (no ViewModel), conforme o hardware do PC.
    public static IReadOnlyList<string> ProfileAppIds(InstallProfile profile) => profile switch
    {
        InstallProfile.Gamer => new[]
        {
            "steam", "discord", "epic", "xbox", "directx", "vcredist_x64", "vcredist_x86", "vcredist_2013",
        },
        InstallProfile.Basic => new[]
        {
            "chrome", "vcredist_x64", "vcredist_x86", "7zip", "vlc",
        },
        InstallProfile.Developer => new[]
        {
            "vscode", "git", "python", "nodejs", "notepadpp",
        },
        InstallProfile.Complete => new[]
        {
            // Componentes essenciais (todas as bibliotecas comuns)
            "vcredist_x64", "vcredist_x86", "vcredist_2013", "vcredist_2013_x86",
            "vcredist_2012_x64", "vcredist_2012_x86", "dotnet_desktop", "directx", "webview2",
            // Mais populares de cada categoria
            "chrome", "discord", "steam", "7zip", "powertoys", "windows_terminal", "sharex",
            "vlc", "spotify", "gimp", "notepadpp", "vscode", "libreoffice", "acrobat_reader", "onedrive",
        },
        _ => Array.Empty<string>(),
    };
}
